src/ISEnglish/Models/ErrorViewModel.cs
namespace ISEnglish.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/ISEnglish/Controllers/HomeController.cs
using ISEnglish.Domain.Core.Models;
using ISEnglish.Domain.Core.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ISEnglish.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }
        
        public IActionResult Index()
        {
            return View();
        }

        [Authorize]
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

    }
}

src/ISEnglish/Controllers/TextsController.cs
using ISEnglish.Domain.Core.Models;
using ISEnglish.Domain.Core.Models.ViewModels;
using ISEnglish.Services.BL;
using ISEnglishMVC.Contracts.Texts;
using ISEnglishMVC.Contracts.Words;
using Microsoft.AspNetCore.Mvc;

namespace ISEnglishMVC.Controllers
{
    public class TextsController : Controller
    {
        private readonly ITextsService _textsService;
        public TextsController(ITextsService textsService)
        {
            _textsService = textsService;
        }
        [HttpGet]
        public async Task<ActionResult> Index(Guid id)
        {
            var texts = await _textsService.GetAllTexts();
            if(id != Guid.Empty)
            {
                var text = await _textsService.GetById(id);
                ViewBag.Text = text;
            }
            var response = texts.Select(b => new TextsResponse(b.Id, b.Name, b.Content));
            ViewBag.Texts = response;
            return View();
        }

        [HttpPost("CreateText")]

        public async Task<ActionResult> CreateText(TextViewModel model)
        {
            if (ModelState.IsValid)
            {
                var textResult = Text.Create(Guid.NewGuid(), model.Name, model.Content);
                if (textResult.IsFailure)
                {
                    return BadRequest(textResult.Error);
                }
                var wordId = await _textsService.CreateText(textResult.Value);
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }

        [HttpPost("DeleteText")]

        public async Task<ActionResult<Guid>> DeleteText(Guid id)
        {
            var result = await _textsService.DeleteText(id);
            return RedirectToAction("Index");
        }


    }
}

src/ISEnglish/Controllers/UsersController.cs
using ISEnglish.Controllers;
using ISEnglish.Domain.Core.Models;
using ISEnglish.Domain.Core.Models.ViewModels;
using ISEnglish.Services.BL;
using ISEnglishMVC.Contracts.Users;
using ISEnglishMVC.Contracts.Words;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NuGet.Common;

namespace ISEnglishMVC.Controllers
{
    public class UsersController : Controller
    {
        private readonly IUserService _userService;
        public UsersController(IUserService userService)
        {
            _userService = userService;
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<ActionResult> Register(RegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (await _userService.IsUniqueUser(model.UserName))
                {
                    await _userService.Register(model.UserName, model.Email, model.Password);
                    return View();
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Invalid register attempt");
                    return RedirectToAction(nameof(HomeController.Index), "Home");
                }
            }
     
            return View(model);
        }
        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<ActionResult> Login(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                var tokenResult = await _userService.Login(model.Email, model.Password);
                if (tokenResult.IsFailure)
                {
                    ModelState.AddModelError(string.Empty, tokenResult.Error);
                    return View(model);
                }
                else
                {
                    Response.Cookies.Append("ts-cookies", tokenResult.Value);
                    return RedirectToAction(nameof(HomeController.Index), "Home");
                }
            }
            return View(model);
           
        }

        public async Task<IActionResult> Logout()
        {
            Response.Cookies.Delete("ts-cookies");
            return RedirectToAction(nameof(HomeController.Index), "Home");
        }

        //[Authorize]
        [HttpGet]
        public async Task<ActionResult<List<UserResponse>>> GetUsers()
        {
            var words = await _userService.GetAllUsers();

            var response = words.Select(b => new UserResponse(b.Id, b.UserName, b.Email, b.PasswordHash));

            return Ok(response);

        }

    //     public IActionResult<bool> IsLogin(){
    //         bool result = false;
    //         System.Console.WriteLine(Response.Cookies.ToString);
    //     }
    }
}

src/ISEnglish/Controllers/WordsController.cs
using ISEnglish.Domain.Core.Models;
using ISEnglish.Domain.Core.Models.ViewModels;
using ISEnglish.Services.BL;
using ISEnglishMVC.Contracts.Words;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;


namespace ISEnglishMVC.Controllers
{
    public class WordsController : Controller
    {


        private readonly IWordsService _wordsService;
        public WordsController(IWordsService wordsService)
        {
            _wordsService = wordsService;

        }

        [HttpGet]
        public async Task<ActionResult<List<WordsResponse>>> Index(string? search)
        {
            var words = await _wordsService.GetAllWords();
            if (!string.IsNullOrWhiteSpace(search))
            {
                words = words.Where(b => (b.RusTitle.ToLower().Contains(search.ToLower()) ||
                                        b.EngTitle.ToLower().Contains(search.ToLower()))).ToList();
            }

            var response = words.Select(b => new WordsResponse(b.Id, b.RusTitle, b.EngTitle, b.Transcription, b.CategoryName));
            ViewBag.Words = response;
            return View();
        }

        [HttpPost("CreateWord")]

        public async Task<ActionResult> CreateWord(WordViewModel model)
        {
            if(ModelState.IsValid){
                var wordResult = Word.Create(Guid.NewGuid(), model.RusTitle, model.EngTitle, $"[{model.Transcription}]", "Category");
                if (wordResult.IsFailure)
                {
                    return BadRequest(wordResult.Error);
                }
                var wordId = await _wordsService.CreateWord(wordResult.Value);
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }

        [HttpPost("DeleteWord")]

        public async Task<ActionResult<Guid>> DeleteWord(Guid id)
        {
            var result = await _wordsService.DeleteWord(id);
            return RedirectToAction("Index");
        }

    }
}

src/ISEnglish/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="main" style="background-image: src(~/Views);">
    <div class="first-block">
        <div class="main-text">
            <p class="mtext-base">English learn UUNIT By <span class="first-text">IS</span></p>
            <p>Discover amazing lessons to expand your word bank and 
                the option to add home reading texts for solidifying 
                new knowledge. Join us, enhance your language skills daily!
            </p>
            <ul>
                <li>Take the tests</li>
                <li>Learn the words</li>
                <li>Add texts to home reading</li>
            </ul>
        </div>
        <div class="main-picture">
            <img src="~/img/9UGATU.jpg" alt="ugatu" height="400px">
        </div>
    </div>
    <div class="second-block">
        <div class="main-text">             
            <p class="smain-text">You can learn <span class="first-text">English!</span></p>
            <p>The learn English Network has been helping people to learn English for free</p>
        </div>
        <div class="cards-container">
            <div class="card">
                <div class="card-img">
                    <img src="https://static.tildacdn.com/tild6634-3964-4233-b535-313765393934/jaredd-craig-HH4WBGN.jpg">
                </div>
                <div class="desc">
                    <p class="primary-text">Home reading</p>
                    <p class="secondary-text">You can add your text and learn it</p>
                </div>
                <form>
                    <button class="button-text" asp-controller="HRead" asp-action="Index"><span class="first-text">H</span>Reading</button>
                </form>
            </div>
            <div class="card">
                <div class="card-img">
                    <img src="https://d2gg9evh47fn9z.cloudfront.net/800px_COLOURBOX18929990.jpg">
                </div>
                <div class="desc">
                    <p class="primary-text">Learn words</p>
                    <p class="secondary-text">You can add and learn your words</p>
                </div>
                <form>
                    <button class="button-text" asp-controller="Words" asp-action="Index"><span class="first-text">L</span>Words</button>
                </form>
            </div>
            <div class="card">
                <div class="card-img">
                    <img src="https://dl.dropbox.com/s/u3j25jx9tkaruap/Webp.net-resizeimage.jpg?raw=1">
                </div>
                <div class="desc">
                    <p class="primary-text">Do tests</p>
                    <p class="secondary-text">You can do tests with your words</p>
                </div>
                <form>
                    <button class="button-text" asp-controller="Tests" asp-action="Index"><span class="first-text">D</span>Tests</button>
                </form>
            </div>
        </div>
        
        <div>
            <p class="bottom-text">The Learn English Network has <span class="bold-text">everything</span> you need to become a <span class="bold-text">confident</span>
                English learner!
            </p>
        </div>
    </div>
</div>

src/ISEnglish/Views/Shared/_Layout.cshtml
@{
    var IsLogin = Context.Request.Cookies["ts-cookies"] != null;
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ISEnglish</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ISEnglish.styles.css" asp-append-version="true" />
</head>

<body>
    <header>
        <nav>
            <div class="header">
                <div class="left-navbar">
                    <div class="logo">
                        <a asp-controller="Home" asp-action="">
                            <span class="first-text">IS</span>
                            <span class="second-text"> English</span>
                        </a>
                    </div>
                    <a asp-controller="Texts" asp-action="Index" class="line-animation">
                        <span class="first-text">H</span><span class="second-text">Reading</span>
                    </a>
                    <a asp-controller="Words" asp-action="Index" class="line-animation">
                        <span class="first-text">L</span><span class="second-text">Words</span>
                    </a>
                    <a href="#" class="line-animation">
                        <span class="first-text">D</span><span class="second-text">Tests</span>
                    </a>
                </div>
                <div class="right-navbar">
                    @if(!IsLogin){
                        <a asp-controller="Users" asp-action="Login" class="login-text">Login</a>
                        <a asp-controller="Users" asp-action="Register" class="register-text">Register</a>
                    }
                    else
                    {
                        <a asp-controller="Users" asp-action="Logout" class="login-text">Logout</a>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer>
        <div class="top-container">
            <div class="foooter-top-text">
                <span>CONTUCT US</span>
                <span>FOLLOW US</span>
            </div>
            <p>
                If you have a question about the Learn English Network
                fill out our <span>Contact Form</span>, and we will get back to you asap.
            </p>
        </div>
        <div class="bottom-container">
            <div class="footer-logo">
                <span class="first-text">IS</span><span class="second-text"> English</span>
            </div>
            <span class="copyriting-text">© Copyright - All Rights Reserved.</span>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

src/ISEnglish/Views/Texts/Index.cshtml
@model ISEnglish.Domain.Core.Models.ViewModels.TextViewModel
@{
    ViewBag.Title = "Home reading";
    var Texts = ViewBag.Texts;
    var Text = ViewBag.Text;
}

<div class="main-texts">
    <div class="side-nav">
        @* <div class="col-md-12">
            <form method="post" asp-action="CreateText">
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Name"></label>
                    <input asp-for="Name" class="form-control" type="text" />
                </div>
                <div class="form-group">
                    <label asp-for="Content"></label>
                    <input asp-for="Content" class="form-control" type="text" />
                </div>
                <button type="submit" class="button-text"><span class="first-text">Add</span> text</button>
            </form>
        </div> *@
        <ul>
            @foreach(var text in Texts)
            {
                <li>
                    <form asp-controller="Texts" method="get">
                        <input class="text-input" type="submit" value="@text.Name" asp-route-id="@text.Id" asp-action="Index" />
                    </form>
                </li>
            }
        </ul>
    </div>
    <div class="content">
        <div class="text-container">
            @if(Text != null)
                {
                    <p class="text-name">
                        @Text.Name
                    </p>
                    <p class="text-content">
                        @Text.Content;
                    </p>
                }
        </div>
    </div>

</div>

src/ISEnglish/Views/Users/Login.cshtml
@model ISEnglish.Domain.Core.Models.LoginViewModel

@{
    ViewBag.Title = "User Login";
}
<div class="login">
    <h1 class="login-text">Login</h1>
    <div class="row">
        <div class="col-md-12">
            <form method="post">
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Email"></label>
                    <input asp-for="Email" class="form-control" />
                </div>
                <div class="form-group">
                    <label asp-for="Password"></label>
                    <input asp-for="Password" class="form-control" />
                </div>
                <div class="form-group">
                    <div class="checkbox">
                        <label asp-for="RememberMe">
                            <input asp-for="RememberMe" />
                            @Html.DisplayNameFor(m => m.RememberMe)
                        </label>
                    </div>
                </div>
                <button type="submit" class="btn">Login</button>
            </form>
        </div>
    </div>
</div>

src/ISEnglish/Views/Users/Register.cshtml
@model ISEnglish.Domain.Core.Models.ViewModels.RegisterViewModel

@{
    ViewBag.Title = "User Register";
}

<div class="register">
    <h1 class="register-text">Register</h1>
    <div class="row">
        <div class="col-md-12">
            <form method="post">
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="UserName"></label>
                    <input asp-for="UserName" class="form-control" />
                </div>
                <div class="form-group">
                    <label asp-for="Email"></label>
                    <input asp-for="Email" class="form-control" />
                </div>
                <div class="form-group">
                    <label asp-for="Password"></label>
                    <input asp-for="Password" class="form-control" />
                </div>

                <button type="submit" class="btn">Register</button>
            </form>
        </div>
    </div>
</div>

src/ISEnglish/Views/Words/Index.cshtml
@model ISEnglish.Domain.Core.Models.ViewModels.WordViewModel
@{
    ViewBag.Title = "Learn Words";
    var Words = ViewBag.Words;
}

<div class="main-words">
    <div class="side-nav">
        <div class="col-md-12">
            <form method="post" asp-action="CreateWord">
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="RusTitle"></label>
                    <input asp-for="RusTitle" class="form-control" type="text" />
                </div>
                <div class="form-group">
                    <label asp-for="EngTitle"></label>
                    <input asp-for="EngTitle" class="form-control" type="text" />
                </div>
                <div class="form-group">
                    <label asp-for="Transcription"></label>
                    <input asp-for="Transcription" class="form-control" type="text" />
                </div>
                <button type="submit" class="button-text"><span class="first-text">Add</span> word</button>
            </form>
        </div>
        <ul>
            <li><a asp-controller="Words">Learn <span class="second-text">words</span></a></li>
            <li><a asp-controller="Words">Tests <span class="second-text">with words</span></a></li>
        </ul>
    </div>
    <div class="content">
        <div class="word-navbar">
            <a>All words</a>
            <form method="get" asp-action="Index">
                <input type="text" class="search" name="search" placeholder="Search"/>
                <input type="submit" hidden="false"/>
            </form>
        </div>
        <div class="words-container">
            <div class="rus-container">
                <p>Russian</p>
                <ul>
                    @foreach (var word in Words)
                    {
                        <li><input class="checkbox" type="checkbox" /> @word.RusTitle</li>
                    }
                </ul>
            </div>
            <div class="eng-container">
                <p>English</p>
                <ul>
                    @foreach (var word in Words)
                    {
                        <li>@word.EngTitle</li>
                    }
                </ul>
            </div>
            <div class="transc-container">
                <p>Transcription</p>
                <ul>
                    @foreach (var word in Words)
                    {
                        <li>
                            <div class="form-width">
                                <span>@word.Transcription</span>
                                <form asp-controller="Words" method="post"><input class="del-input" type="submit" value="Delete" asp-route-id="@word.Id" asp-action="DeleteWord" /></form>
                            </div>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </div>

</div>

src/ISEnglish/Views/Words/Words.cshtml
@model ISEnglish.Domain.Core.Models.Word

@{
    ViewBag.Title = "Learn Words";
}

<div class="main">
    <div class="side-nav">
        <ul>
            <li><a asp-controller="Words">All words</a></li>
            <li><a asp-controller="Words">Learn words</a></li>
            <li><a asp-controller="Words">Add word</a></li>
            <li><a asp-controller="Words">Tests with words</a></li>
        </ul>
    </div>

</div>